# 1-A

In [72]:
import os
import numpy as np
from PIL import Image
lenna_path = os.path.join(os.getcwd(),'Lenna.png')
lenna_path

'/Users/mark/kaist/Lenna.png'

In [73]:
from PIL import Image

In [74]:
lenn_img = Image.open(lenna_path)

In [75]:
lenn_arr = np.array(lenn_img)
lenn_arr.shape

(512, 512, 3)

In [76]:
def color_to_gray(img):
    r = img[:,:,0]
    g = img[:,:,1]
    b = img[:,:,2]
    gray = r*0.2989 + g*0.5870 + b*0.1140
    return gray

In [77]:
gray_lenn=color_to_gray(lenn_arr)
print(gray_lenn.shape)

(512, 512)


## 1-B

## 1-B-i

In [78]:
"""
w_list = [1/16*i for i in [1,2,1,2,4,2,1,2,1]] #np.zeros(shape=(3,3))
w_list
w = np.reshape(np.array(w_list),(3,3))

"""

'\nw_list = [1/16*i for i in [1,2,1,2,4,2,1,2,1]] #np.zeros(shape=(3,3))\nw_list\nw = np.reshape(np.array(w_list),(3,3))\n\n'

In [79]:
def get_sub_img(img,x,y):
    
    sub_img = np.zeros_like(img[1:4,1:4])
    sub_img = img[x-1:x+2,y-1:y+2]
    
    return sub_img

def mask_product(w,img,x,y):
    sub_img = get_sub_img(img,x,y)
    res = np.sum(w*sub_img)
    if res < 0:
        res =  np.absolute(res)
        assert res >= 0.0
        #print('negative detected & pos_val:'+str(res))
    if res > 255.0:
        return 255.0
    return res

def image_with_gauss(img):
    w_list = [1/16*i for i in [1,2,1,2,4,2,1,2,1]] #np.zeros(shape=(3,3))
    w = np.reshape(np.array(w_list),(3,3))
    
    _img = np.zeros((512+2,512+2))
    _img[1:513,1:513] = img
    
    new_image = []
    
    for i in range(1,513):
        for j in range(1,513):
            res = mask_product(w,_img,i,j)
            
            new_image.append(res)

    new_image = np.reshape(np.array(new_image),(512,512))
    return new_image

In [80]:
gaussian_lenn =image_with_gauss(gray_lenn)
gaussian_lenn

array([[ 91.248975  , 121.66816875, 121.45696875, ..., 124.76184375,
        113.9058375 ,  77.10241875],
       [121.6653    , 162.224225  , 161.942625  , ..., 166.349125  ,
        151.87445   , 102.803225  ],
       [121.6653    , 162.224225  , 161.942625  , ..., 166.349125  ,
        151.87445   , 102.803225  ],
       ...,
       [ 32.8116375 ,  45.56244375,  48.6113875 , ..., 101.959375  ,
        101.28553125,  75.27291875],
       [ 32.6773125 ,  46.02725   ,  50.132425  , ..., 102.8704375 ,
        104.1998625 ,  78.71550625],
       [ 24.7060125 ,  34.9334625 ,  38.30930625, ...,  77.3691375 ,
         79.0483875 ,  60.17791875]])

In [81]:
gaussian_lenn.max()

234.27640624999998

In [82]:
print(gaussian_lenn.shape)
262144 == 512*512

(512, 512)


True

## 1-B-ii

In [84]:
def image_with_sobel1(img): # img 는 gaussian_filtering 된 lenna 여야한다
    w_list = [-1,-2,-1,0,0,0,1,2,1]
    w = np.reshape(np.array(w_list),(3,3))
    
    _img = np.zeros((512+2,512+2))
    _img[1:513,1:513] = img
    
    new_image = []
    
    for i in range(1,513):
        for j in range(1,513):
            res = mask_product(w,_img,i,j)
            
            new_image.append(res)

    new_image = np.reshape(np.array(new_image),(512,512))
    return new_image

def image_with_sobel2(img): # img 는 gaussian_filtering 된 lenna 여야한다
    w_list = [-1,0,1,-2,0,2,-1,0,1]
    w = np.reshape(np.array(w_list),(3,3))
    
    _img = np.zeros((512+2,512+2))
    _img[1:513,1:513] = img
    
    new_image = []
    
    for i in range(1,513):
        for j in range(1,513):
            res = mask_product(w,_img,i,j)
            
            new_image.append(res)

    new_image = np.reshape(np.array(new_image),(512,512))
    return new_image

In [85]:
sobel1_lenn = image_with_sobel1(gaussian_lenn)
print(sobel1_lenn.shape)
print(sobel1_lenn.max())
sobel1_lenn

(512, 512)
255.0


array([[2.55000000e+02, 2.55000000e+02, 2.55000000e+02, ...,
        2.55000000e+02, 2.55000000e+02, 2.55000000e+02],
       [1.01388706e+02, 1.52014094e+02, 1.61941775e+02, ...,
        1.63773494e+02, 1.43225312e+02, 8.93702250e+01],
       [2.84217094e-14, 0.00000000e+00, 0.00000000e+00, ...,
        5.68434189e-14, 0.00000000e+00, 0.00000000e+00],
       ...,
       [6.72699375e+00, 3.98648750e+00, 3.98820625e+00, ...,
        1.88907438e+01, 2.38214187e+01, 2.02363812e+01],
       [2.68402312e+01, 3.96656688e+01, 4.21585312e+01, ...,
        9.50641812e+01, 8.41595250e+01, 5.24271437e+01],
       [1.11381875e+02, 1.74864238e+02, 1.98240900e+02, ...,
        2.55000000e+02, 2.55000000e+02, 2.55000000e+02]])

In [86]:
sobel2_lenn = image_with_sobel2(gaussian_lenn)
print(sobel2_lenn.shape)
print(sobel2_lenn.max())
sobel2_lenn

(512, 512)
255.0


array([[255.        , 100.6933125 ,   1.4165    , ...,  46.6170625 ,
        158.86475   , 255.        ],
       [255.        , 151.03996875,   2.12475   , ...,  69.92559375,
        238.297125  , 255.        ],
       [255.        , 161.1093    ,   2.2664    , ...,  74.5873    ,
        254.1836    , 255.        ],
       ...,
       [184.71409375,  62.2345125 ,  18.05566875, ...,   4.30040625,
        104.68008125, 255.        ],
       [172.55040625,  64.31326875,  21.45874375, ...,   7.64319375,
         92.1875375 , 255.        ],
       [115.894175  ,  44.6617    ,  15.2407875 , ...,   6.74780625,
         58.53736875, 255.        ]])

## 3

In [99]:
weights = np.reshape(np.array([0,10,15,20,5,0,9,10,6,13,0,12,8,8,9,0]),(4,4))
weights

array([[ 0, 10, 15, 20],
       [ 5,  0,  9, 10],
       [ 6, 13,  0, 12],
       [ 8,  8,  9,  0]])

## 4

In [4]:
import os
import numpy as np
from PIL import Image

dat_path = os.path.join(os.getcwd(),'prob4.dat')
dat_img = np.fromfile(dat_path, dtype=np.uint8) #Image.open(dat_path)
dat_img = np.reshape(dat_img,(300,200))
print(dat_img.shape)
dat_img

(300, 200)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [5]:
def get_group(img,s_coord):
    group_members = [s_coord]
    #t_coord = s_coord
    
    #while len(get_candidates(img,t_coord)) != 0:
    c = get_candidates(img,s_coord)
    if len(c) == 0:
        return []

    for _c in c:
        group_members.extend(get_group(img,_c))
    return group_members
    #while len(group_members.extend(get_candidates(img,)))

def is_white(img,coord):
    if img[coord[0],coord[1]] == 255.0:
        #print('is_white')
        return True
    return False


def get_candidates(img,coord): # 하나의 흰점에서 뻗치기
    candidates=[]
    
    x,y = coord
    x_min = x-1
    x_max = x+1
    y_min = y-1
    y_max = y+1
    if x == 0:
        x_min = x
    if y == 0:
        y_min = y
    if x == 299:
        x_max = 299
    if y == 199:
        y_max = 199
    
    for i in range(x+1,x_max+1):
        for j in range(y+1,y_max+1):
            if is_white(img,(i,j)):
                candidates.append((i,j))
    """if is_white(img, (x+1,y)):
        candidates.append((x+1,y))
    if is_white(img, (x,y+1)):
        candidates.append((x,y+1))
    if is_white(img, (x+1,y+1)):
        candidates.append((x+1,y+1))
    if is_white(img,(x-1,y+1)):
        candidates.append((x-1,y+1))
    if is_white(img,(x-1,y)):
        candidates.append((x-1,y))"""
    
    return candidates

def groups(img):
    groups = []
    for i in range(300):
        for j in range(200):
            if is_white(img,(i,j)):
                is_in = False
                for g in groups:
                    if (i,j) in g:
                        is_in = True
                        break
                if not is_in:
                    groups.append(get_group(img,(i,j)))
    #print(len(groups))
    return groups

def color_img(img):
    _img = img.copy()
    _groups = groups(_img)
    
    for idx, g in enumerate(_groups):
        color = float(idx+1)
        for c in g:
            _img[c[0],c[1]] = color
    return _img


In [6]:
colored_dat_img = color_img(dat_img)
colored_dat_img

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [7]:
np.mean(dat_img) == np.mean(colored_dat_img)

False

In [8]:
np.mean(dat_img)

97.7925

In [9]:
np.mean(colored_dat_img) # 46.48113333333333

46.48113333333333

# 2

In [70]:
n = 10
import sys
#rl = lambda sys.system...

s = [1,5,2,1,4,3,4,5,2,1]
size = len(s)

d = [[0]*len(s) for _ in range(len(s))]
d

for i in range(size):
    d[i][i] = 1
    if i < size-1:
        d[i][i+1] = 2
    for j in range(size):
        if i > j:
            d[i][j] = -1

d

for i in range(2,size):
    for j in range(i+1,size):
        #pass
        #print((i,j))
        max_idx = s.index(max(s[i:j+1]))
        min_idx = s.index(min(s[i:j+1]))
        
        """if max(s[i:j+1]) == s[j] or s[j-1] > s[j]:
            d[i][j] = d[i][j-1] + 1
        else:
            d[i][j] = d[i][j-1]"""
d

s[3:2+1]

[]